In [3]:
import sys
import numpy as np

print("Python: {}".format(sys.version))
print("Numpy: {}".format(np.__version__))

Python: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Numpy: 1.14.5


In [4]:
# defining a scalar
x = 7
x

7

In [6]:
# defining a vector
x = np.array((1,2,3))
x


array([1, 2, 3])

In [8]:
print ("Vector Dimensions: {}".format(x.shape))
print ("Vector Size: {}".format(x.size))

Vector Dimensions: (3,)
Vector Size: 3


In [10]:
# defining a matrix
x = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
print("Matrix Dimensions: {}".format(x.shape))
print("Matrix Size: {}".format(x.size))

Matrix Dimensions: (3, 3)
Matrix Size: 9


In [17]:
# define a matrix of a given dimension
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
print("Matrix Dimensions: {}".format(x.shape))
print("Matrix Size: {}".format(x.size))

Matrix Dimensions: (3, 3)
Matrix Size: 9


In [20]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
print("Tensor Dimensions: {}".format(x.shape))
print("Tensor Size: {}".format(x.size))

Tensor Dimensions: (3, 3, 3)
Tensor Size: 27


In [25]:
# indexing
A = np.ones((5,5), dtype = np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [27]:
# indexing starts at zero
A[0,1] = 2
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [28]:
A[:,0] = 3
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [29]:
A[:,:] = 5
print(A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [31]:
# for higher dimensions, simply add and index
A = np.ones((5,5,5), dtype = np.int)

# assign first row a new value
A[:,0,0] = 6
print(A)

[[[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [32]:
# matrix operations
A = np.matrix([[1,2], [3,4]])
B = np.ones((2,2), dtype = np.int)


In [33]:
print(A)

[[1 2]
 [3 4]]


In [34]:
print(B)

[[1 1]
 [1 1]]


In [38]:
# Element wise sum
C = A + B
print(C)

[[2 3]
 [4 5]]


In [36]:
# Element wise subtraction
C = A - B
print(C)

[[0 1]
 [2 3]]


In [39]:
# matrix multiplication
C = A * B
print(C)

[[3 3]
 [7 7]]


In [40]:
# the matrix transpose
A = np.array(range(9))
A = A.reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [42]:
B = A.T
print(B)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [43]:
C = B.T
print(C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
A = np.array(range(10))
A = A.reshape(2,5)
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [45]:
B = A.T
print(B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [46]:
print(B.shape)
print(A.shape)

(5, 2)
(2, 5)


In [50]:
# tensors!
A = np.ones((3,3,3,3,3,3,3,3,3,3))

print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
